name: VHS

on:
  push:
    branches: [main]
    paths:
      - demo/*.tape
  workflow_dispatch:

jobs:
  vhs:
    name: Render Demo GIF
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0

      - uses: pnpm/action-setup@0ebf47130e4866e96fce0953f49152a61190b271 # v6.0.9

      - uses: actions/setup-node@249970729cb0ef3589644e2896645e5dc5ba9c38 # v6
        with:
          node-version: 24
          cache: pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Render
        uses: charmbracelet/vhs-action@59641cdc7fadf3978db65eb8c6937ea2752f4ec3 # v2
        with:
          path: demo/preview.tape

      - name: Commit GIF
        uses: EndBug/add-and-commit@290ea2c423ad77ca9c62ae0f5b224379612c0321 # v10
        with:
          message: 'chore: update demo gif [skip ci]'
          add: demo/terminal.gif
