name: VHS

on:
  push:
    branches: [main]
    paths:
      - demo/*.tape
  workflow_dispatch:

jobs:
  vhs:
    name: Render Demo GIF
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - uses: pnpm/action-setup@8912a9102ac27614460f54aedde9e1e7f9aec20d # v6

      - uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6
        with:
          node-version: 22
          cache: pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Render
        uses: charmbracelet/vhs-action@59641cdc7fadf3978db65eb8c6937ea2752f4ec3 # v2
        with:
          path: demo/preview.tape

      - name: Commit GIF
        uses: EndBug/add-and-commit@290ea2c423ad77ca9c62ae0f5b224379612c0321 # v10
        with:
          message: 'chore: update demo gif [skip ci]'
          add: demo/terminal.gif
